### ISSUE TITLE
another one?

### ISSUE THREAD

**Issue by vitaly-t** [jakoblorz/postgres-driver#18]
check out this one: https://github.com/sweetiq/schemats

it sounds very familiar :wink:

**Comment by jakoblorz** [comment]
hahaha :+1: - yes you are right it does currently look pretty familiar (only that this module advertises the **use of classes**)

### short background about this module
In a private project currently in production I am using a self-written module that is using **lodash-chain styled sql query construction functions** (wow much words) to improve readability. The module I used there cannot be made open-source as it contains confidential information - the structure is pretty bad also (it was written during a 24h coding session, it was unclear if it would work after all).
So this module is an ongoing effort to abstract, rewrite and open-source this code-base!
Thus the expected features for **v2.0.0** are:
- use [schemats]( https://github.com/sweetiq/schemats) to generate types (this is why there might be some familiarity)
- lodash-chain styled sql query construction functions (where run is async thus awaitable): 
```typescript 
await this.select("account_id", "username").from(this.name).where({account_id: id}).limit(1).run();
await this.insert({account_id: id, username: "user"}).into(this.name).run();
await this.update(this.name).set({username: "friend"}).where({account_id: id}).run();
await this.delete(this.name).where({account_id: id}).run();
```
- intelligent/intuitive type recommendations
- based on the amazing [pg-promise](https://github.com/vitaly-t/pg-promise) module (yes it is amazing @vitaly-t :wink: )

All this might take some time because the summer-break in Germany is over and I now need to concentrate on my classes - I created this repo just because I wanted to push something out already :smile:

**Comment by jakoblorz** [comment]
So if somebody is afraid that this is *another one* :disappointed:, then I advise him to just ignore it. 
I am also aware that I did not communicate the above before.

Because it is not complete from my perspective, this module it is not listed on [npm](https://www.npmjs.com/) yet :boom:
